### ISSUE TITLE
Problem with installation of ram_ba_package

### ISSUE THREAD

**Issue by reevebox** [ceesietopc/ram_ba_package#1]
I'm using ROS Jade and Ubuntu 14.04 LTS. Ram_ba_package's downloaded from github. When run catkin_make to get error:
 /catkin_ws/src/ram_ba_package/src/controller.cpp:32:30: fatal error: ram/nonlinearity.h: No such file  or directory
  #include <ram/nonlinearity.h>
How to solve it?
Thanks.

**Comment by ceesietopc** [comment]
Hi Reevebox! I was able to recreate this problem and fixed it in the last commit. Please let me know if this fixed your problem. 

I'd love to hear where you are going to use the software for as well, by the way! ;)

**Comment by reevebox** [comment]
Hi Cees!
Problem solved. Package is installed successfully.Thank you.
I want to test the PD controller and repeat the experiments in the implementation, which I read in your article on the site of the University of Twente.

**Comment by ceesietopc** [comment]
Nice to hear, thanks for getting back to me! Good luck with your experiments and let me know if I can help.
